nms:
  name: No Man's Sky
  source: C:\Users\andre\AppData\Roaming\HelloGames\NMS\st_76561197970753391
  destinations:
    - C:\Game Saves\NMS Backup
    - \\Valhalla\Andrew\Game Saves\NMS Backup
  replace: true

borderlands 3:
  name: Borderlands 3
  source: D:\Users\andrew\Documents\My Games\Borderlands 3\Saved
  destinations:
    - C:\Game Saves\Borderlands 3 Backup
    - \\Valhalla\Andrew\Game Saves\Borderlands 3 Backup
  replace: true

factorio:
  name: Factorio
  source: C:\Users\andre\AppData\Roaming\Factorio\saves
  destinations:
    - C:\Game Saves\Factorio Backup
    - \\Valhalla\Andrew\Game Saves\Factorio Backup
  replace: true