test:
  name: Test
  source: /mnt/d/dev/go-copy-testing-ground/source
  destinations:
    - /mnt/d/dev/go-copy-testing-ground/destinationOne
    - /mnt/d/dev/go-copy-testing-ground/destinationTwo
  replace: always
